// This file is generated by Slice Machine. Update with care!

import Benefits from './Benefits';
import Cards from './Cards';
import Contacts from './Contacts';
import Faq from './Faq';
import Features from './Features';
import Hero from './Hero';
import Image from './Image';
import PricePage from './PricePage';
import Prices from './Prices';
import SuccessPage from './SuccessPage';
import Testimonials from './Testimonials';
import TextWithFeatures from './TextWithFeatures';
import TextWithImage from './TextWithImage';

export {
	Benefits,
	Cards,
	Contacts,
	Faq,
	Features,
	Hero,
	Image,
	PricePage,
	Prices,
	SuccessPage,
	Testimonials,
	TextWithFeatures,
	TextWithImage,
};

export const components = {
	benefits: Benefits,
	cards: Cards,
	contacts: Contacts,
	faq: Faq,
	features: Features,
	hero: Hero,
	image: Image,
	price_page: PricePage,
	prices: Prices,
	success_page: SuccessPage,
	testimonials: Testimonials,
	text_with_features: TextWithFeatures,
	text_with_image: TextWithImage,
};
