// This file is generated by Slice Machine. Update with care!

import Benefits from './Benefits';
import Features from './Features';
import Hero from './Hero';
import Image from './Image';
import Prices from './Prices';
import Testimonials from './Testimonials';
import TextWithFeatures from './TextWithFeatures';
import TextWithImage from './TextWithImage';

export {
	Benefits,
	Features,
	Hero,
	Image,
	Prices,
	Testimonials,
	TextWithFeatures,
	TextWithImage,
};

export const components = {
	benefits: Benefits,
	features: Features,
	hero: Hero,
	image: Image,
	prices: Prices,
	testimonials: Testimonials,
	text_with_features: TextWithFeatures,
	text_with_image: TextWithImage,
};
